"""nullable resume_id on tailoring_jobs with ondelete SET NULL

Revision ID: b30f639f830c
Revises: 2e9f4abffa23
Create Date: 2026-03-12 20:50:43.049949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30f639f830c'
down_revision: Union[str, Sequence[str], None] = '2e9f4abffa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tailoring_jobs', 'resume_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('tailoring_jobs_resume_id_fkey'), 'tailoring_jobs', type_='foreignkey')
    op.create_foreign_key('tailoring_jobs_resume_id_fkey', 'tailoring_jobs', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tailoring_jobs_resume_id_fkey', 'tailoring_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('tailoring_jobs_resume_id_fkey'), 'tailoring_jobs', 'resumes', ['resume_id'], ['id'])
    op.alter_column('tailoring_jobs', 'resume_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
