"""initial

Revision ID: f11a4c601796
Revises: 
Create Date: 2026-03-04 12:32:00.434769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # add this

# revision identifiers, used by Alembic.
revision: str = 'f11a4c601796'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('auth_token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_token'), 'users', ['auth_token'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('phase', sa.Enum('analysis', 'resume_generation', 'cover_letter_app_answers', 'calibrate', 'compare', 'interview_prep', name='promptphase'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_user_id'), 'prompt_templates', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_analysis', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'analyzing', 'complete', name='sessionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('jds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compensation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employee_count', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'apply', 'maybe', 'no', name='jdstatus'), nullable=True),
    sa.Column('status_source', sa.Enum('ai', 'user', name='jdstatussource'), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('requirements_met', sa.JSON(), nullable=True),
    sa.Column('app_questions', sa.Text(), nullable=True),
    sa.Column('additional_jd_text', sa.Text(), nullable=True),
    sa.Column('cover_letter_requested', sa.Boolean(), nullable=False),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jds_session_id'), 'jds', ['session_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jd_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.Enum('application', 'phone_screen', 'interview_1', 'interview_2', 'interview_3', 'interview_4', 'interview_5', 'interview_6', 'interview_7', 'offer', 'reject', 'follow_up', 'prep_doc', 'prep_time', 'thank_you', 'post_mortem', name='activitytype'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['jds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_jd_id'), 'activities', ['jd_id'], unique=False)
    op.create_table('tailoring_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jd_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'ready', 'reviewed', name='tailoringstatus'), nullable=True),
    sa.Column('output_resume', sa.Text(), nullable=True),
    sa.Column('output_cover_letter', sa.Text(), nullable=True),
    sa.Column('output_app_answers', sa.JSON(), nullable=True),
    sa.Column('output_resume_docx', sa.LargeBinary(), nullable=True),
    sa.Column('chat_context', sa.JSON(), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_cost_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jd_id'], ['jds.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailoring_jobs_jd_id'), 'tailoring_jobs', ['jd_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailoring_jobs_jd_id'), table_name='tailoring_jobs')
    op.drop_table('tailoring_jobs')
    op.drop_index(op.f('ix_activities_jd_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_jds_session_id'), table_name='jds')
    op.drop_table('jds')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_prompt_templates_user_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_token'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
