"""
ApplicationPipeline data model.

Seven core entities. Foreign keys are explicit. No deep nesting —
TailoringJob belongs to JD, not Session (see ADR-004).
Activity belongs to JD — each row is a to-do that happened (or hasn't yet).
"""

import enum
from datetime import date, datetime
from typing import Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import ForeignKey, JSON, Uuid
from sqlmodel import Column, Enum, Field, SQLModel, Text


# ── Enums ────────────────────────────────────────────────────────────────────

class PromptPhase(str, enum.Enum):
    """
    The four tailoring phases are composable pieces of a single API call:
      analysis + resume_generation + (optionally) cover_letter + (optionally) app_answers
    Each gets its own editable text box in the UI and its own PromptTemplate row.
    At tailoring time, they're concatenated in order into one prompt.

    cover_letter and app_answers are toggled independently per JD:
      - cover_letter: included only if jd.cover_letter_requested
      - app_answers:  included only if jd.app_questions is populated

    The rest (calibrate, compare, interview_prep) are standalone workflow phases.

    History: cover_letter + app_answers were originally one phase
    (cover_letter_app_answers). Split in ADR-012 for independent toggle
    conditions and UI separation. The old Postgres enum value is retained
    (can't DROP VALUE) but never referenced in code.
    """
    # Composable tailoring pieces (assembled into one Claude call)
    analysis = "analysis"
    resume_generation = "resume_generation"          # includes docx formatting instructions (ADR-011)
    cover_letter = "cover_letter"                    # optional, toggled per JD
    app_answers = "app_answers"                      # optional, toggled per JD
    # Standalone workflow phases
    calibrate = "calibrate"
    compare = "compare"
    interview_prep = "interview_prep"


class SessionStatus(str, enum.Enum):
    active = "active"
    analyzing = "analyzing"
    complete = "complete"


class JDStatus(str, enum.Enum):
    pending = "pending"
    apply = "apply"
    maybe = "maybe"
    no = "no"


class JDStatusSource(str, enum.Enum):
    ai = "ai"
    user = "user"


class TailoringStatus(str, enum.Enum):
    queued = "queued"
    processing = "processing"
    ready = "ready"
    reviewed = "reviewed"
    failed = "failed"


class ActivityType(str, enum.Enum):
    """
    Lean vocabulary. Adding a value is a one-line Alembic migration:
        op.execute("ALTER TYPE activitytype ADD VALUE 'new_thing'")
    Removing/renaming is harder (full enum recreation), so start lean, grow as needed.
    """
    # Pipeline stages (the main interview funnel)
    application = "application"
    phone_screen = "phone_screen"
    interview_1 = "interview_1"
    interview_2 = "interview_2"
    interview_3 = "interview_3"
    interview_4 = "interview_4"
    interview_5 = "interview_5"
    interview_6 = "interview_6"
    interview_7 = "interview_7"
    offer = "offer"
    reject = "reject"
    # Action items (generated by service layer cascades or added manually)
    follow_up = "follow_up"
    prep_doc = "prep_doc"
    prep_time = "prep_time"
    thank_you = "thank_you"
    post_mortem = "post_mortem"


# ── Models ───────────────────────────────────────────────────────────────────

class User(SQLModel, table=True):
    __tablename__ = "users"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    email: Optional[str] = Field(default=None, index=True)
    auth_token: str = Field(index=True)  # cookie-based, always present
    created_at: datetime = Field(default_factory=datetime.utcnow)
    auth_token_expires_at: Optional[datetime] = Field(
        default=None
    )  # 7 days for anonymous, null for accounts


class Resume(SQLModel, table=True):
    """
    Text-only for Phase 0. Users paste resume content directly; it's
    editable and viewable in the app as plain text. Claude sees this text
    for analysis and tailoring.

    Phase N: add a resume uploader tab that accepts binary files (docx/pdf),
    analyzes formatting, and feeds style preferences into generation.
    """

    __tablename__ = "resumes"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", index=True)
    label: str  # user-assigned, e.g. "Technical", "Leadership"
    content: str = Field(sa_column=Column(Text))  # the resume text, editable in-app
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Max 3 per user — enforced at the API layer, not the DB.


class PromptTemplate(SQLModel, table=True):
    __tablename__ = "prompt_templates"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: Optional[UUID] = Field(
        default=None, foreign_key="users.id", index=True
    )  # null = system default
    phase: PromptPhase = Field(sa_column=Column(Enum(PromptPhase)))
    name: str  # user-facing label
    template_text: str = Field(sa_column=Column(Text))  # {jd_text}, {resume}, etc.
    version: int = Field(default=1)  # auto-increment per user+phase
    is_active: bool = Field(default=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Session(SQLModel, table=True):
    """
    One session = one metadata set (board + filters + search_term).
    New metadata = new session. Keeps funnel analytics clean (ADR-006).
    """

    __tablename__ = "sessions"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", index=True)
    board: str  # LinkedIn, Indeed, etc.
    filters: str  # "remote, last 24 hours" — free text
    search_term: str  # the keyword used
    meta_analysis: Optional[str] = Field(
        default=None, sa_column=Column(Text)
    )  # Claude's rolling cross-JD summary
    status: SessionStatus = Field(
        default=SessionStatus.active,
        sa_column=Column(Enum(SessionStatus)),
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)


class JD(SQLModel, table=True):
    __tablename__ = "jds"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    session_id: UUID = Field(foreign_key="sessions.id", index=True)
    number: int  # position in session (1–25), maps to job board order

    # Text
    raw_text: str = Field(sa_column=Column(Text))
    cleaned_text: str = Field(sa_column=Column(Text))

    # Extracted / user-entered metadata
    company: str = Field(default="")
    role: str = Field(default="")
    compensation: Optional[str] = None
    employee_count: Optional[str] = None
    link: Optional[str] = None

    # Status
    status: JDStatus = Field(
        default=JDStatus.pending,
        sa_column=Column(Enum(JDStatus)),
    )
    status_source: JDStatusSource = Field(
        default=JDStatusSource.ai,
        sa_column=Column(Enum(JDStatusSource)),
    )

    # Analysis
    analysis_text: Optional[str] = Field(
        default=None, sa_column=Column(Text)
    )
    requirements_met: Optional[Any] = Field(
        default=None, sa_column=Column(JSON)
    )  # [{requirement, status, notes}]

    # Enrichment (Stage 2)
    app_questions: Optional[str] = Field(default=None, sa_column=Column(Text))
    additional_jd_text: Optional[str] = Field(default=None, sa_column=Column(Text))
    cover_letter_requested: bool = Field(default=False)
    flagged_for_review: bool = Field(default=False)  # sends to Calibrate tab

    created_at: datetime = Field(default_factory=datetime.utcnow)


class TailoringJob(SQLModel, table=True):
    """
    Belongs to JD, not Session (ADR-004). Tailoring jobs outlive their
    session context — interview prep happens days or weeks later.
    """

    __tablename__ = "tailoring_jobs"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    jd_id: UUID = Field(foreign_key="jds.id", index=True)
    resume_id: UUID | None = Field(
        default=None,
        sa_column=Column(
            Uuid, ForeignKey("resumes.id", ondelete="SET NULL"), nullable=True
        ),
    )  # nullable: resume deletion sets this to NULL, outputs remain accessible
    prompt_snapshot: str = Field(sa_column=Column(Text))  # frozen at kick-off

    status: TailoringStatus = Field(
        default=TailoringStatus.queued,
        sa_column=Column(Enum(TailoringStatus)),
    )

    # Outputs — Claude produces the docx directly (formatting instructions are
    # in the prompt, not a separate template layer). output_resume stores a text
    # copy EXTRACTED FROM the generated docx for in-app display and comparison.
    # Data flow: prompt → Claude → docx → extract text → output_resume.
    # NOT: prompt → Claude → text → format into docx.
    output_resume: Optional[str] = Field(default=None, sa_column=Column(Text))
    output_cover_letter: Optional[str] = Field(default=None, sa_column=Column(Text))
    output_app_answers: Optional[Any] = Field(
        default=None, sa_column=Column(JSON)
    )  # [{question, answer}]
    # bytes auto-maps to LargeBinary (Postgres bytea) in SQLModel/SQLAlchemy.
    # No explicit Column(LargeBinary) needed — if you see VARCHAR in a migration,
    # something went wrong with the auto-mapping and you need to add it back.
    output_resume_docx: Optional[bytes] = None

    # Context
    chat_context: Optional[Any] = Field(
        default=None, sa_column=Column(JSON)
    )  # structured context for continuation
    model_used: str = Field(default="claude-opus-4-6")
    api_cost_cents: Optional[int] = None

    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None


class Activity(SQLModel, table=True):
    """
    An activity is a to-do that happened (or hasn't yet).

    completed_at IS NULL = your to-do list. Order by due_date for priority.
    Time-to-hire = MAX(completed_at) - MIN(completed_at) per JD.
    Weekly counts = GROUP BY week derived from due_date or completed_at.

    Pipeline stages (application, phone_screen, interview_N, offer, reject)
    and action items (follow_up, prep_doc, thank_you, etc.) live in the same
    table. Action items are auto-generated by service-layer cascades when a
    user logs a pipeline stage — e.g. scheduling interview_1 creates prep_doc,
    prep_time, thank_you, and post_mortem activities with offset due dates.
    """

    __tablename__ = "activities"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    jd_id: UUID = Field(foreign_key="jds.id", index=True)
    activity_type: ActivityType = Field(sa_column=Column(Enum(ActivityType)))
    due_date: Optional[date] = None  # null = no deadline (e.g. "waiting on reply")
    completed_at: Optional[datetime] = None  # null = still a to-do
    notes: Optional[str] = Field(default=None, sa_column=Column(Text))
    created_at: datetime = Field(default_factory=datetime.utcnow)
