#!/usr/bin/env python3
"""Generate .dockerignore from .gitignore + .dockerignore.extra, then prove Docker excludes what git ignores.

Both source files are held to a dialect that git and Docker read identically, so generating
is plain concatenation. There is no translator to trust.

  python scripts/sync_dockerignore.py           lint, regenerate, check this working tree for leaks
  python scripts/sync_dockerignore.py --check   lint, fail if .dockerignore is stale (CI; writes nothing)
  python scripts/sync_dockerignore.py --fix     rewrite the mechanical lint failures first, then run
"""
import os
import subprocess
import sys
from pathlib import Path

GITIGNORE = Path(".gitignore")
EXTRA = Path(".dockerignore.extra")
DOCKERIGNORE = Path(".dockerignore")

HEADER = """\
# GENERATED by scripts/sync_dockerignore.py. Don't edit this file.
# Rules git and Docker share live in .gitignore. Docker-only rules live in .dockerignore.extra.
"""


def git(*args):
    return subprocess.run(["git", *args], check=True, capture_output=True, text=True).stdout.splitlines()


def read(path):
    return path.read_text(encoding="utf-8").splitlines() if path.exists() else []  # splitlines eats CRLF too


def write(path, text):
    with path.open("w", encoding="utf-8", newline="\n") as f:  # LF on every OS, so --check agrees everywhere
        f.write(text)


def is_rule(line):
    return bool(line.strip()) and not line.startswith("#")


# ---------------------------------------------------------------- the dialect

def problems(line, source):
    """One check per place where git and Docker read the same text differently."""
    if not is_rule(line):
        return []
    body = line.strip().removeprefix("!")
    found = []
    if line != line.strip():
        found.append("edge whitespace: Docker trims it, git keeps leading spaces")
    if any(ch.isspace() for ch in body):
        found.append("space inside: a trailing '# note' is part of the pattern in both")
    if any(ch in body for ch in "[]\\"):
        found.append("[ ] or \\: character classes and escapes differ")
    if body.endswith("/"):
        found.append("trailing /: git means directories only, Docker drops it")
    if "/" not in body.rstrip("/"):
        found.append("no /: git matches any depth, Docker only the root (write **/name or /name)")
    if any("**" in part and part != "**" for part in body.split("/")):
        found.append("** inside a name: only **/x, x/**/y and x/** mean the same in both")
    if source == EXTRA and line.startswith("!"):
        found.append("! in extras: it could re-include something .gitignore excludes")
    return found


def dead_negations(lines):
    """git can't re-include a path inside an excluded folder, but Docker can. Catches the literal case."""
    earlier, found = set(), []
    for n, line in enumerate(lines, 1):
        if not is_rule(line):
            continue
        if not line.startswith("!"):
            earlier.add(line)
            continue
        parts = line[1:].lstrip("/").split("/")
        for i in range(1, len(parts)):
            folder = "/".join(parts[:i])
            if {folder, "/" + folder, "**/" + folder} & earlier:
                found.append(f".gitignore:{n}: git won't re-include inside excluded '{folder}' (Docker will). "
                             f"Exclude '{folder}/*' instead.")
                break
    return found


def fixed(line, source):
    """Rewrites that keep each file's own meaning. Anything riskier stays for a human."""
    s = line.strip()
    if not is_rule(s):
        return s
    neg, body = ("!", s[1:]) if s.startswith("!") else ("", s)
    body = body.rstrip("/")  # widens 'dir/' (dirs only) to 'dir' (file or dir), which only ignores more
    if body and "/" not in body:
        # .gitignore meant "any depth". The extras were written in Docker terms, where a bare name means the root.
        body = ("**/" if source == GITIGNORE else "/") + body
    return neg + body


# ---------------------------------------------------------------- generate + verify

def render():
    out = [HEADER, "\n# ---- .gitignore ----\n"]
    out += [line + "\n" for line in read(GITIGNORE)]
    # Extras go last. Docker lets the last matching line win, so extras can re-exclude what a
    # .gitignore '!' let back in, and the '!' ban keeps them from loosening anything.
    out += ["\n# ---- .dockerignore.extra ----\n"]
    out += [line + "\n" for line in read(EXTRA)]
    return "".join(out)


def leaks():
    """Paths git ignores in this working tree that .dockerignore would still send to Docker.

    The dialect makes git a faithful reader of .dockerignore, so this needs no Docker. It also
    sees rules the generator can't: nested .gitignore files (uv writes .venv/.gitignore),
    .git/info/exclude, and your global excludesFile. A fresh clone has nothing to find, so CI skips it.
    """
    ignored = git("ls-files", "--others", "--ignored", "--exclude-standard", "--directory")
    # Force case-sensitive matching for Docker's side: a Linux builder is, even when a Mac's git isn't
    excluded = set(git("-c", "core.ignorecase=false", "ls-files", "--others", "--ignored",
                       f"--exclude-from={DOCKERIGNORE}", "--directory"))
    dirs = tuple(p for p in excluded if p.endswith("/"))
    missing = [p for p in ignored if p not in excluded and not p.startswith(dirs)]
    # git can list a directory and then its contents; report only the top-most path
    return [p for p in missing if not any(q != p and q.endswith("/") and p.startswith(q) for q in missing)]


def main(args):
    os.chdir(git("rev-parse", "--show-toplevel")[0])

    if "--fix" in args:
        for path in (GITIGNORE, EXTRA):
            if path.exists():
                text = "".join(fixed(line, path) + "\n" for line in read(path))
                write(path, text)

    errors = [f"{path}:{n}: {why}\n    {line!r}"
              for path in (GITIGNORE, EXTRA)
              for n, line in enumerate(read(path), 1)
              for why in problems(line, path)]
    if errors:
        errors.append("(--fix rewrites edge whitespace, trailing /, and bare names. The rest need you.)")
    errors += dead_negations(read(GITIGNORE))
    # The generator reads only the root .gitignore, so a committed nested one would be skipped silently
    errors += [f"{p}: committed nested .gitignore. Move its rules into the root .gitignore."
               for p in git("ls-files", "*/.gitignore")]
    if errors:
        print(*errors, sep="\n", file=sys.stderr)
        return 1

    want = render()
    have = DOCKERIGNORE.read_text(encoding="utf-8") if DOCKERIGNORE.exists() else ""
    if "--check" in args:
        if have != want:
            print(".dockerignore is stale. Run: python scripts/sync_dockerignore.py", file=sys.stderr)
            return 1
        return 0

    if have != want:
        write(DOCKERIGNORE, want)
        print("rewrote .dockerignore")

    found = leaks()
    if found:
        print("git ignores these, but Docker would still get them:", file=sys.stderr)
        print(*(f"  {p}" for p in found), sep="\n", file=sys.stderr)
        print("Cover each with a line in .gitignore or .dockerignore.extra.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
